### PR TITLE
Ensure PortalTarget onChange is called on initial render

### LINKED ISSUE #527: onChange doesn't fire on initial render
I'm not sure if this is related to #10 or not, but we recently found that a hard refresh of our app on a page that renders at least one portal _does not_ call the `onChange` function that's passed to `PortalTarget`. We worked around this by moving our updating to use the yielded `count` which _does_ have the right value.

Is this a bug or intended behavior?

### PR DESCRIPTION
**Pull request by meirish**
Fixes #527.

### CODE REVIEW

**Comment by meirish** [comment]
I looked into this a bit, but wasn't sure how you'd prefer to fix it.

The issue seems to be that because of the `next` wrapping here https://github.com/kaliber5/ember-stargate/blob/2f55bd96bccea7e3414c33b2ec92526cb2738a70/packages/ember-stargate/src/services/-portal.ts#L48 when registering the `PortalTarget`, that means that `target` here: https://github.com/kaliber5/ember-stargate/blob/2f55bd96bccea7e3414c33b2ec92526cb2738a70/packages/ember-stargate/src/services/-portal.ts#L65 is `undefined` so the `onChange` doesn't get called.

**Comment by simonihmig** [comment]
Thanks for the test! There are some linting errors, could you please fix them? (you can run `yarn lint` locally)

Your observations regarding `next()` make a lot of sense. I don't really recall why I used that in the first place. Will look into it...

**Review by simonihmig — APPROVED** [review]
All tests pass! :tada: 

Thank you!

**Comment by simonihmig** [comment]
https://github.com/kaliber5/ember-stargate/releases/tag/v0.4.3

**Pull request merged**
